"""initial_schema

Revision ID: 6f7d1e0cabfe
Revises: ff061e70b231
Create Date: 2026-06-22 00:52:10.446293+00:00

This migration is autogenerated + manually patched. Manual fixes (see commit
message and CLAUDE.md > Conventions):

* All ``CREATE TYPE`` for Postgres ENUMs are emitted up-front, exactly once,
  so shared enums (``reaction_kind``) don't double-create.
* GIN ``jsonb_path_ops`` indexes for ``content`` columns
  (``articles``, ``messages``, ``direct_messages``).
* GIN indexes for ``mentioned_user_ids`` arrays.
* GIN ``gin_trgm_ops`` indexes for ``users.username`` and
  ``user_profiles.display_name``.
* GiST index on ``messages.path`` (``ltree``).
* GENERATED ALWAYS AS STORED ``content_tsv`` columns + GIN indexes on them
  (we drop the plain TSVECTOR autogenerate produces and recreate as
  GENERATED — SQLAlchemy can't model this natively).
* ``use_alter=True`` FKs are already produced by autogenerate; we keep them.

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.modules.messages.types

# revision identifiers, used by Alembic.
revision: str = "6f7d1e0cabfe"
down_revision: str | None = "ff061e70b231"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Enum definitions (created once, up-front, referenced via create_type=False)
# ---------------------------------------------------------------------------

USER_ROLE = postgresql.ENUM(
    "user", "moderator", "admin", "agent", name="user_role", create_type=False
)
BAN_SCOPE = postgresql.ENUM(
    "global", "section", "topic", name="ban_scope", create_type=False
)
ARTICLE_STATUS = postgresql.ENUM(
    "draft", "published", "archived", "hidden", name="article_status",
    create_type=False,
)
MESSAGE_STATUS = postgresql.ENUM(
    "visible", "edited", "hidden_by_mod", "deleted_by_author",
    name="message_status", create_type=False,
)
REACTION_KIND = postgresql.ENUM(
    "brain", "synapse", "neuron", "microscope", "dna", "mindblown", "petri",
    "lightbulb", name="reaction_kind", create_type=False,
)
MENTION_SOURCE_TYPE = postgresql.ENUM(
    "article", "message", "direct_message", name="mention_source_type",
    create_type=False,
)
CONVERSATION_KIND = postgresql.ENUM(
    "dm", "group", name="conversation_kind", create_type=False
)
DIRECT_MESSAGE_STATUS = postgresql.ENUM(
    "visible", "edited", "deleted_by_author", name="direct_message_status",
    create_type=False,
)
ATTACHMENT_KIND = postgresql.ENUM(
    "image", "gif", "video", "file", name="attachment_kind", create_type=False
)
ATTACHMENT_PROCESSING_STATUS = postgresql.ENUM(
    "pending", "ready", "failed", name="attachment_processing_status",
    create_type=False,
)
EXTERNAL_SOURCE_TYPE = postgresql.ENUM(
    "arxiv", "biorxiv", "doi", "pubmed", "custom", name="external_source_type",
    create_type=False,
)
AI_PROPOSAL_ACTION = postgresql.ENUM(
    "draft", "expand", "rephrase", "summarize", "cite_check", "translate",
    "outline", name="ai_proposal_action", create_type=False,
)
AI_PROPOSAL_STATUS = postgresql.ENUM(
    "pending", "accepted", "rejected", "expired", name="ai_proposal_status",
    create_type=False,
)
LLM_PROVIDER = postgresql.ENUM(
    "openrouter", "cloud_ru", "anthropic_direct", "openai_direct",
    name="llm_provider", create_type=False,
)
LLM_USAGE_STATUS = postgresql.ENUM(
    "success", "error", "rate_limited", "budget_exceeded",
    name="llm_usage_status", create_type=False,
)

ALL_ENUMS = [
    USER_ROLE, BAN_SCOPE, ARTICLE_STATUS, MESSAGE_STATUS, REACTION_KIND,
    MENTION_SOURCE_TYPE, CONVERSATION_KIND, DIRECT_MESSAGE_STATUS,
    ATTACHMENT_KIND, ATTACHMENT_PROCESSING_STATUS, EXTERNAL_SOURCE_TYPE,
    AI_PROPOSAL_ACTION, AI_PROPOSAL_STATUS, LLM_PROVIDER, LLM_USAGE_STATUS,
]


def upgrade() -> None:
    # ---- 1. Create every ENUM type exactly once --------------------------
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ---- 2. Create tables (autogenerated) --------------------------------
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", CONVERSATION_KIND, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("dm_key", sa.String(length=73), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("dm_key", name=op.f("uq_conversations_dm_key")),
    )
    op.create_table(
        "embeds",
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ttl_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("url_hash", name=op.f("pk_embeds")),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("slug", name=op.f("uq_sections_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", USER_ROLE, server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "agent_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", LLM_PROVIDER, nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("encrypted_api_key", sa.LargeBinary(), nullable=False),
        sa.Column("key_fingerprint", sa.String(length=16), nullable=False),
        sa.Column("default_model", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("monthly_budget_usd", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "spent_this_month",
            sa.Numeric(precision=10, scale=4),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_agent_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_credentials")),
        sa.UniqueConstraint(
            "user_id",
            "display_name",
            name="uq_agent_credentials_user_id_display_name",
        ),
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("uploader_id", sa.UUID(), nullable=False),
        sa.Column("kind", ATTACHMENT_KIND, nullable=False),
        sa.Column(
            "bucket",
            sa.String(length=50),
            server_default="forum-media",
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("poster_object_key", sa.String(length=500), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column(
            "processing_status",
            ATTACHMENT_PROCESSING_STATUS,
            server_default="ready",
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploader_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("object_key", name=op.f("uq_attachments_object_key")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_action_created",
        "audit_log",
        ["action", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_actor_created",
        "audit_log",
        ["actor_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_target",
        "audit_log",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "conversation_participants",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("muted_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_participants_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversation_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "conversation_id", "user_id", name="pk_conversation_participants"
        ),
    )
    op.create_index(
        "ix_conversation_participants_user_id_joined_at",
        "conversation_participants",
        ["user_id", sa.literal_column("joined_at DESC")],
        unique=False,
    )
    op.create_table(
        "direct_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_text", sa.Text(), server_default="", nullable=False),
        sa.Column("reply_to_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            DIRECT_MESSAGE_STATUS,
            server_default="visible",
            nullable=False,
        ),
        sa.Column(
            "attachments",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_direct_messages_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_direct_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["direct_messages.id"],
            name=op.f("fk_direct_messages_reply_to_id_direct_messages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_direct_messages")),
    )
    op.create_index(
        "ix_direct_messages_author_id_created_at",
        "direct_messages",
        ["author_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_direct_messages_conversation_id_created_at",
        "direct_messages",
        ["conversation_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "mentions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_type", MENTION_SOURCE_TYPE, nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("mentioned_user_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_mentions_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["mentioned_user_id"],
            ["users.id"],
            name=op.f("fk_mentions_mentioned_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mentions")),
        sa.UniqueConstraint(
            "source_type",
            "source_id",
            "mentioned_user_id",
            name="uq_mentions_source_user",
        ),
    )
    op.create_index(
        "ix_mentions_mentioned_created",
        "mentions",
        ["mentioned_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_mentions_source",
        "mentions",
        ["source_type", "source_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_unread_created",
        "notifications",
        ["user_id", "is_read", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("uq_refresh_tokens_token_hash")
        ),
    )
    op.create_index(
        "ix_refresh_tokens_user_id_expires_at",
        "refresh_tokens",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_locked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_topics_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_topics_section_id_sections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("section_id", "slug", name="uq_topics_section_id_slug"),
    )
    op.create_index(
        "ix_topics_section_id_is_pinned_created_at",
        "topics",
        ["section_id", "is_pinned", "created_at"],
        unique=False,
    )
    op.create_table(
        "user_bans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("banned_by", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("scope", BAN_SCOPE, nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column(
            "starts_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifted_by", sa.UUID(), nullable=True),
        sa.Column("lift_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'global'  AND section_id IS NULL AND topic_id IS NULL) OR "
            "(scope = 'section' AND section_id IS NOT NULL AND topic_id IS NULL) OR "
            "(scope = 'topic'   AND section_id IS NULL AND topic_id IS NOT NULL)",
            name=op.f("ck_user_bans_scope_target_consistency"),
        ),
        sa.ForeignKeyConstraint(
            ["banned_by"], ["users.id"], name=op.f("fk_user_bans_banned_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["lifted_by"], ["users.id"], name=op.f("fk_user_bans_lifted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name="fk_user_bans_section_id_sections",
            ondelete="CASCADE",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name="fk_user_bans_topic_id_topics",
            ondelete="CASCADE",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_bans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_bans")),
    )
    op.create_index(
        "ix_user_bans_user_id_expires_at",
        "user_bans",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("orcid", sa.String(length=19), nullable=True),
        sa.Column(
            "social_links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("locale", sa.String(length=10), server_default="ru", nullable=False),
        sa.Column("timezone", sa.String(length=50), server_default="UTC", nullable=False),
        sa.CheckConstraint(
            r"orcid IS NULL OR orcid ~ '^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$'",
            name=op.f("ck_user_profiles_orcid_format"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "articles_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "messages_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "received_reactions_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "saved_articles_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_stats_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_stats")),
    )
    op.create_table(
        "agents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column(
            "allowed_actions",
            postgresql.ARRAY(sa.String(length=50)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["agent_credentials.id"],
            name=op.f("fk_agents_credential_id_agent_credentials"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_agents_owner_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_agents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_agents")),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_text", sa.Text(), server_default="", nullable=False),
        # Plain TSVECTOR column — replaced below with a GENERATED column.
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            server_default=sa.text("''"),
            nullable=True,
        ),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("status", ARTICLE_STATUS, server_default="draft", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "mentioned_user_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "reaction_counts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_articles_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_articles_topic_id_topics"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("topic_id", "slug", name="uq_articles_topic_id_slug"),
    )
    op.create_index(
        "ix_articles_topic_id_status_published_at",
        "articles",
        ["topic_id", "status", "published_at"],
        unique=False,
    )
    op.create_table(
        "attachment_usages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attachment_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_attachment_usages_attachment_id_attachments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment_usages")),
        sa.UniqueConstraint(
            "attachment_id",
            "entity_type",
            "entity_id",
            name="uq_attachment_usages_attachment_id_entity_type_entity_id",
        ),
    )
    op.create_index(
        "ix_attachment_usages_entity_type_entity_id",
        "attachment_usages",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "direct_message_reads",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column(
            "read_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["direct_messages.id"],
            name=op.f("fk_direct_message_reads_message_id_direct_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_direct_message_reads_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "message_id", name="pk_direct_message_reads"
        ),
    )
    op.create_table(
        "article_ai_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("action", AI_PROPOSAL_ACTION, nullable=False),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "proposed_content",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "proposed_diff",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "status",
            AI_PROPOSAL_STATUS,
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.user_id"],
            name="fk_article_ai_proposals_agent_id_agents",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_ai_proposals_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_article_ai_proposals_decided_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_article_ai_proposals_requested_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_ai_proposals")),
    )
    op.create_index(
        "ix_article_ai_proposals_article_id_status_created_at",
        "article_ai_proposals",
        ["article_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_article_ai_proposals_expires_at",
        "article_ai_proposals",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "article_reactions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("kind", REACTION_KIND, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_reactions_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_article_reactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "article_id", "kind", name="pk_article_reactions"
        ),
    )
    op.create_table(
        "article_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("editor_id", sa.UUID(), nullable=False),
        sa.Column("editor_role_at_edit", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("edit_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_revisions_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_article_revisions_editor_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_revisions")),
        sa.UniqueConstraint(
            "article_id", "revision", name="uq_article_revisions_article_id_revision"
        ),
    )
    op.create_table(
        "external_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=True),
        sa.Column("source", EXTERNAL_SOURCE_TYPE, nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_external_sources_article_id_articles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_sources")),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_external_sources_source_external_id"
        ),
    )
    op.create_index(
        "ix_external_sources_article_id",
        "external_sources",
        ["article_id"],
        unique=False,
    )
    op.create_table(
        "llm_usage_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("proposal_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", LLM_USAGE_STATUS, nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.user_id"],
            name=op.f("fk_llm_usage_log_agent_id_agents"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_llm_usage_log_conversation_id_conversations",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["agent_credentials.id"],
            name=op.f("fk_llm_usage_log_credential_id_agent_credentials"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["article_ai_proposals.id"],
            name="fk_llm_usage_log_proposal_id_article_ai_proposals",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_usage_log")),
    )
    op.create_index(
        "ix_llm_usage_log_agent_id_created_at",
        "llm_usage_log",
        ["agent_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_llm_usage_log_credential_id_created_at",
        "llm_usage_log",
        ["credential_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("thread_root_id", sa.UUID(), nullable=True),
        sa.Column("depth", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("path", app.modules.messages.types.Ltree(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_text", sa.Text(), server_default="", nullable=False),
        # Plain TSVECTOR column — replaced below with a GENERATED column.
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            server_default=sa.text("''"),
            nullable=True,
        ),
        sa.Column(
            "reply_to_selection", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status", MESSAGE_STATUS, server_default="visible", nullable=False
        ),
        sa.Column(
            "mentioned_user_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "reaction_counts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_messages_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_messages_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["messages.id"],
            name=op.f("fk_messages_parent_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_root_id"],
            ["messages.id"],
            name=op.f("fk_messages_thread_root_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_article_created_at",
        "messages",
        ["article_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_messages_author_created_at",
        "messages",
        ["author_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_messages_parent_created_at",
        "messages",
        ["parent_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "saved_articles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column(
            "saved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_saved_articles_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_articles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "article_id", name="pk_saved_articles"),
    )
    op.create_index(
        "ix_saved_articles_user_saved_at",
        "saved_articles",
        ["user_id", sa.literal_column("saved_at DESC")],
        unique=False,
    )
    op.create_table(
        "message_reactions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("kind", REACTION_KIND, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_reactions_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_message_reactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "message_id", "kind", name="pk_message_reactions"
        ),
    )
    op.create_table(
        "message_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("editor_id", sa.UUID(), nullable=False),
        sa.Column("editor_role_at_edit", sa.String(length=20), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("edit_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_message_revisions_editor_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_revisions_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_revisions")),
        sa.UniqueConstraint(
            "message_id", "revision", name="uq_message_revisions_message_id_revision"
        ),
    )

    # ---- 3. Manual extras: GIN/GiST/trgm indexes -------------------------
    # JSONB GIN indexes on content columns.
    op.create_index(
        "ix_articles_content_gin",
        "articles",
        ["content"],
        postgresql_using="gin",
        postgresql_ops={"content": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_messages_content_gin",
        "messages",
        ["content"],
        postgresql_using="gin",
        postgresql_ops={"content": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_direct_messages_content_gin",
        "direct_messages",
        ["content"],
        postgresql_using="gin",
        postgresql_ops={"content": "jsonb_path_ops"},
    )

    # GIN indexes on UUID[] mentioned_user_ids.
    op.create_index(
        "ix_articles_mentioned_user_ids_gin",
        "articles",
        ["mentioned_user_ids"],
        postgresql_using="gin",
    )
    op.create_index(
        "ix_messages_mentioned_user_ids_gin",
        "messages",
        ["mentioned_user_ids"],
        postgresql_using="gin",
    )

    # Trigram fuzzy search indexes.
    op.create_index(
        "ix_users_username_trgm",
        "users",
        ["username"],
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_user_profiles_display_name_trgm",
        "user_profiles",
        ["display_name"],
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )

    # B-tree index on users.role — agent filtering.
    op.create_index("ix_users_role", "users", ["role"], unique=False)

    # GiST index on messages.path (ltree subtree queries).
    op.create_index(
        "ix_messages_path_gist",
        "messages",
        ["path"],
        postgresql_using="gist",
    )

    # ---- 4. GENERATED tsvector columns -----------------------------------
    # autogenerate produced a plain TSVECTOR column; drop & recreate as
    # GENERATED ALWAYS AS STORED so writes can never desync.
    op.drop_column("articles", "content_tsv")
    op.execute(
        "ALTER TABLE articles "
        "ADD COLUMN content_tsv tsvector "
        "GENERATED ALWAYS AS (to_tsvector('russian', coalesce(content_text, ''))) STORED"
    )
    op.create_index(
        "ix_articles_content_tsv",
        "articles",
        ["content_tsv"],
        postgresql_using="gin",
    )

    op.drop_column("messages", "content_tsv")
    op.execute(
        "ALTER TABLE messages "
        "ADD COLUMN content_tsv tsvector "
        "GENERATED ALWAYS AS (to_tsvector('russian', coalesce(content_text, ''))) STORED"
    )
    op.create_index(
        "ix_messages_content_tsv",
        "messages",
        ["content_tsv"],
        postgresql_using="gin",
    )


def downgrade() -> None:
    # ---- Drop manual extras first ----------------------------------------
    op.drop_index("ix_messages_content_tsv", table_name="messages")
    op.drop_column("messages", "content_tsv")
    # Recreate the plain TSVECTOR column so the model still matches.
    op.add_column(
        "messages",
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            server_default=sa.text("''"),
            nullable=True,
        ),
    )

    op.drop_index("ix_articles_content_tsv", table_name="articles")
    op.drop_column("articles", "content_tsv")
    op.add_column(
        "articles",
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            server_default=sa.text("''"),
            nullable=True,
        ),
    )

    op.drop_index("ix_messages_path_gist", table_name="messages")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index(
        "ix_user_profiles_display_name_trgm", table_name="user_profiles"
    )
    op.drop_index("ix_users_username_trgm", table_name="users")
    op.drop_index("ix_messages_mentioned_user_ids_gin", table_name="messages")
    op.drop_index("ix_articles_mentioned_user_ids_gin", table_name="articles")
    op.drop_index("ix_direct_messages_content_gin", table_name="direct_messages")
    op.drop_index("ix_messages_content_gin", table_name="messages")
    op.drop_index("ix_articles_content_gin", table_name="articles")

    # ---- Drop tables in reverse FK-safe order ----------------------------
    op.drop_table("message_revisions")
    op.drop_table("message_reactions")
    op.drop_index("ix_saved_articles_user_saved_at", table_name="saved_articles")
    op.drop_table("saved_articles")
    op.drop_index("ix_messages_parent_created_at", table_name="messages")
    op.drop_index("ix_messages_author_created_at", table_name="messages")
    op.drop_index("ix_messages_article_created_at", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "ix_llm_usage_log_credential_id_created_at", table_name="llm_usage_log"
    )
    op.drop_index(
        "ix_llm_usage_log_agent_id_created_at", table_name="llm_usage_log"
    )
    op.drop_table("llm_usage_log")
    op.drop_index("ix_external_sources_article_id", table_name="external_sources")
    op.drop_table("external_sources")
    op.drop_table("article_revisions")
    op.drop_table("article_reactions")
    op.drop_index(
        "ix_article_ai_proposals_expires_at", table_name="article_ai_proposals"
    )
    op.drop_index(
        "ix_article_ai_proposals_article_id_status_created_at",
        table_name="article_ai_proposals",
    )
    op.drop_table("article_ai_proposals")
    op.drop_table("direct_message_reads")
    op.drop_index(
        "ix_attachment_usages_entity_type_entity_id", table_name="attachment_usages"
    )
    op.drop_table("attachment_usages")
    op.drop_index(
        "ix_articles_topic_id_status_published_at", table_name="articles"
    )
    op.drop_table("articles")
    op.drop_table("agents")
    op.drop_table("user_stats")
    op.drop_table("user_profiles")
    op.drop_index("ix_user_bans_user_id_expires_at", table_name="user_bans")
    op.drop_table("user_bans")
    op.drop_index(
        "ix_topics_section_id_is_pinned_created_at", table_name="topics"
    )
    op.drop_table("topics")
    op.drop_index("ix_refresh_tokens_user_id_expires_at", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_notifications_user_unread_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_mentions_source", table_name="mentions")
    op.drop_index("ix_mentions_mentioned_created", table_name="mentions")
    op.drop_table("mentions")
    op.drop_index(
        "ix_direct_messages_conversation_id_created_at", table_name="direct_messages"
    )
    op.drop_index(
        "ix_direct_messages_author_id_created_at", table_name="direct_messages"
    )
    op.drop_table("direct_messages")
    op.drop_index(
        "ix_conversation_participants_user_id_joined_at",
        table_name="conversation_participants",
    )
    op.drop_table("conversation_participants")
    op.drop_index("ix_audit_log_target", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_created", table_name="audit_log")
    op.drop_index("ix_audit_log_action_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("attachments")
    op.drop_table("agent_credentials")
    op.drop_table("users")
    op.drop_table("sections")
    op.drop_table("embeds")
    op.drop_table("conversations")

    # ---- Drop ENUM types in reverse order --------------------------------
    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
